<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Dashboard Report</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: 'Arial', sans-serif;
            font-size: 12px;
            color: #333;
            line-height: 1.6;
        }
        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 20px;
            margin-bottom: 20px;
        }
        .header h1 {
            font-size: 24px;
            margin-bottom: 5px;
        }
        .header p {
            font-size: 12px;
            opacity: 0.9;
        }
        .meta-info {
            background: #f8f9fa;
            padding: 10px;
            margin-bottom: 20px;
            border-left: 4px solid #667eea;
        }
        .stats-grid {
            display: table;
            width: 100%;
            margin-bottom: 20px;
        }
        .stat-row {
            display: table-row;
        }
        .stat-box {
            display: table-cell;
            width: 25%;
            padding: 15px;
            background: #f8f9fa;
            border: 1px solid #e9ecef;
            text-align: center;
        }
        .stat-label {
            font-size: 10px;
            color: #6c757d;
            text-transform: uppercase;
            margin-bottom: 5px;
        }
        .stat-value {
            font-size: 20px;
            font-weight: bold;
            color: #333;
        }
        .section {
            margin-bottom: 25px;
            page-break-inside: avoid;
        }
        .section-title {
            font-size: 14px;
            font-weight: bold;
            margin-bottom: 10px;
            padding-bottom: 5px;
            border-bottom: 2px solid #667eea;
            color: #667eea;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        th {
            background: #f8f9fa;
            padding: 8px;
            text-align: left;
            font-weight: bold;
            border-bottom: 2px solid #dee2e6;
            font-size: 11px;
        }
        td {
            padding: 8px;
            border-bottom: 1px solid #e9ecef;
            font-size: 11px;
        }
        .text-right {
            text-align: right;
        }
        .text-center {
            text-align: center;
        }
        .badge {
            display: inline-block;
            padding: 3px 8px;
            border-radius: 3px;
            font-size: 10px;
            font-weight: bold;
        }
        .badge-success {
            background: #d4edda;
            color: #155724;
        }
        .badge-danger {
            background: #f8d7da;
            color: #721c24;
        }
        .progress-bar {
            width: 100%;
            height: 20px;
            background: #e9ecef;
            border-radius: 3px;
            overflow: hidden;
            position: relative;
        }
        .progress-fill {
            height: 100%;
            background: #667eea;
            display: inline-block;
        }
        .footer {
            margin-top: 30px;
            padding-top: 10px;
            border-top: 1px solid #dee2e6;
            text-align: center;
            font-size: 10px;
            color: #6c757d;
        }
    </style>
</head>
<body>
    <!-- Header -->
    <div class="header">
        <h1>📊 Dashboard Report</h1>
        <p>{{ $filterLabel }} • Generated: {{ $generatedAt }}</p>
    </div>

    <!-- Meta Info -->
    <div class="meta-info">
        <strong>Period:</strong> {{ \Carbon\Carbon::parse($startDate)->format('d/m/Y') }} - {{ \Carbon\Carbon::parse($endDate)->format('d/m/Y') }}
        <br>
        <strong>Generated by:</strong> {{ auth()->user()->name }}
    </div>

    <!-- Statistics -->
    <div class="section">
        <div class="section-title">Key Statistics</div>
        <div class="stats-grid">
            <div class="stat-row">
                <div class="stat-box">
                    <div class="stat-label">Total Revenue</div>
                    <div class="stat-value">Rp {{ number_format($stats['totalRevenue'], 0, ',', '.') }}</div>
                </div>
                <div class="stat-box">
                    <div class="stat-label">Total Products</div>
                    <div class="stat-value">{{ $stats['totalProducts'] }}</div>
                </div>
                <div class="stat-box">
                    <div class="stat-label">Transactions</div>
                    <div class="stat-value">{{ $stats['totalTransactions'] }}</div>
                </div>
                <div class="stat-box">
                    <div class="stat-label">Low Stock Alert</div>
                    <div class="stat-value" style="color: #dc3545;">{{ $stats['lowStockCount'] }}</div>
                </div>
            </div>
        </div>
    </div>

    <!-- Sales Trend -->
    <div class="section">
        <div class="section-title">Sales Trend</div>
        <table>
            <thead>
                <tr>
                    <th>Date</th>
                    <th class="text-right">Revenue</th>
                </tr>
            </thead>
            <tbody>
                @foreach($salesChart as $day)
                <tr>
                    <td>{{ $day['date'] }}</td>
                    <td class="text-right">Rp {{ number_format($day['revenue'], 0, ',', '.') }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <!-- Best Selling Products -->
    <div class="section">
        <div class="section-title">Best Selling Products (Top 5)</div>
        <table>
            <thead>
                <tr>
                    <th>Product Name</th>
                    <th class="text-center">Units Sold</th>
                    <th class="text-right">Revenue</th>
                </tr>
            </thead>
            <tbody>
                @foreach($bestProducts as $product)
                <tr>
                    <td>{{ $product->name }}</td>
                    <td class="text-center">{{ $product->sold }}</td>
                    <td class="text-right">Rp {{ number_format($product->revenue, 0, ',', '.') }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <!-- Top Categories -->
    <div class="section">
        <div class="section-title">Top 10 Categories by Revenue</div>
        <table>
            <thead>
                <tr>
                    <th>Category</th>
                    <th class="text-right">Revenue</th>
                    <th style="width: 40%;">Performance</th>
                </tr>
            </thead>
            <tbody>
                @php
                    $maxValue = $categoryStats->max('value');
                @endphp
                @foreach($categoryStats as $category)
                <tr>
                    <td>{{ $category->name }}</td>
                    <td class="text-right">Rp {{ number_format($category->value, 0, ',', '.') }}</td>
                    <td>
                        <div class="progress-bar">
                            <div class="progress-fill" style="width: {{ ($category->value / $maxValue) * 100 }}%;"></div>
                        </div>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <!-- Recent Transactions -->
    <div class="section">
        <div class="section-title">Recent Transactions</div>
        <table>
            <thead>
                <tr>
                    <th>Transaction ID</th>
                    <th>Date</th>
                    <th>Time</th>
                    <th>Cashier</th>
                    <th class="text-right">Total</th>
                </tr>
            </thead>
            <tbody>
                @foreach($recentTransactions as $transaction)
                <tr>
                    <td>#{{ $transaction->id }}</td>
                    <td>{{ \Carbon\Carbon::parse($transaction->date)->format('d/m/Y') }}</td>
                    <td>{{ $transaction->time }}</td>
                    <td>{{ $transaction->cashier->name }}</td>
                    <td class="text-right">Rp {{ number_format($transaction->total, 0, ',', '.') }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <!-- Footer -->
    <div class="footer">
        <p>SIPIM - Store Information & Management System</p>
        <p>This report is generated automatically. For more information, please contact your system administrator.</p>
    </div>
</body>
</html>